### ISSUE TITLE
Hydrodyn as standalone driver

### ISSUE THREAD

**Issue by TiasaGhosh** [NWTC/HydroDyn#1]
Hello everyone,
I want to run HydroDyn as standalone driver. I cloned the repository and I have got the whole repo except for the bin folder. How do I get the driver for HydroDyn? 
I am using cygwin. I have earlier used InflowWind standalone driver and would get the executable directly upon downloading the code folder.
thank you!
Regards,
Tiasa

**Comment by jjonkman** [comment]
Hi @TiasaGhosh,

First, I would recommend using the OpenFAST repo, which is more up-to-date, then this old-NWTC archive site.  HydroDyn is included in the OpenFAST repo: https://github.com/OpenFAST/openfast.

That said, while the OpenFAST repo does include precompiled Windows executables for OpenFAST (https://github.com/OpenFAST/openfast/releases), it does not include precompiled executables for the standalone module-level drivers.  It does, however, include the source code and compile scripts to compile the standalone module-level driver code if that is what you need.

But because you are on this old archive site, perhaps you want to access an older version of HydroDyn?  In that case, you can also access the old archive of HydroDyn that was included in FAST v8.16 here: https://drive.google.com/drive/folders/1VxgOK7NoFUg9-KZRoYOc1VS9GQFVSnSr.

Best regards,

**Comment by TiasaGhosh** [comment]
Hello Dr. Jonkman,
previously I thought of running HydroDyn module as a standalone driver since I wanted to try a different floater modelled in AQWA and run in HydroDyn first without any other external influence.
However, later on, I switched off CompInflow, CompAero, CompServo in OpenFAST input file to isolate the HydroDyn and work on that.
Thank you for your suggestion. I will use this in near future. 👍 :) 
Best reagrds,
Tiasa
